title: To promote cryptocurrency
description: Cryptocurrency investor.
template:
  repo: to-promote-cryptocurrency-template
  name: to-promote-cryptocurrency
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
